# -*- coding: utf-8 -*-
"""Session-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MJG07lMv4U9vDzDgo8BrmxpC2nHj8v5
"""



"""###  Python Output"""

print("I am winner over myself")

print("I have to win everyday over myself")

print("i challenged myself for", 180, " days without any fun for making myself better ")

print("i challenged myself for 180 days without any fun for making myself better ")

print(180, "days hard challenge")

"""sep="..." it shows , what we want to put at the place of space"""

print(180, "days", sep='/')

print(180)
print("days")

print(180, end="-")
print("days")

print(180,"days", end="\n")
print("ji")

print(180, end="\n")
print("days")

"""## Data types"""

# integer
print(9)
print(1e308)

#Decimal/Float

print(8.55)
print(1.7e308)

#Boolean

print(True)
print(False)

#Text/String

print("Hello world")

#complex
print(5+6j)

# List-->Array
print([1,2,3,4,"set"])

#Tuple
print((1,2,3,4,5,"set"))

#set
print({1,2.4,5,6,"set"})

#Dictionary
print({"Power":"self-control","Rule":"Consistent and discipline","Goal":"complete your daily target"})

"""### type function : it tells about the DATA TYPE"""

type(1)

type(2.5)

type((1,1,5,6,7))

type(True)

"""## Variables
variables are containers for future work
"""

name= "power"
print(name)

# we creat multiple variable together
a,b,c=2,3,5
print(a,b,c)

a=b=c=5
print(a,b,c)

"""### Comments"""

"""
Two types of comments line
1. single line comment :- #
2. Multi line comment :- (\"""..........\""")
"""

"""### Keywords and Identifiers"""

# Keywords :- some words reserved for compiler and interpreter
 # Identifiers:- As a programer , we need to create name, that name is called identifiers

"""## User Input"""

input("Enter Email : ")

"""Take 2 number from user and add them"""

# Steps



# take input from user and store
num1=int(input("Enter first number"))
num2=int(input("Enter second number"))
# add them
result=num1+num2
# print the result
print(result)

# Type conversion

 print(float(5))

 print(int(100.5))

 print(str(5))

"""## Literals

"""

# There are some way to store literals

# 1. integer literals
a = 0b1010  #  binary literals
b=100  #Decimal literals
c=0o310 #Octal literals
d= 0x12c #Hexadecimal literal


# 2.Float literals

a=1.5
b=1.5e2 # 1.5 * 10^2
c=1.5e-3 #1.5*10^-3

# 3. complex literals

x=5+3.14j
print(x, x.imag, x.real)



#string literals

string = 'This'
strings ="This"
char = 'c'
multiline_str="""This is a multiline string with
 more than one line code."""
#unicode = u"\u00dcnic\u00f6de"
unicode = u"\U0001f600\U0001F606\U0001F923"
raw_str = r"raw \n string"


print(string)
print(strings)
print(char)
print(multiline_str)
print(unicode)
print(raw_str)

#Boolean literals

x= True + 4
y= False +10
print(x)
print(y)

a=None
print(a)

k=None
a=5
b=6
print("program execution")

"""### Q1 :- Print the given strings as per stated format.

**Given strings:**
"""

"Data" "Science" "Mentorship" "Program"
"By" "CampusX"

"""Output"""

# Data-Science-Mentorship-Program-started-By-CampusX

"""###Answer"""

# Write your code here
print("Data","Science","Mentorship","program", sep="-", end="-")
print("By","CompusX",sep="-")

"""###Q2:- Write a program that will convert celsius value to fahrenheit."""

# Write your code here
cel=input("Enter the value of celcius:")
celcius=float(cel)
deg_f = (9/5 * celcius) +32
print(deg_f)

"""### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax."""

# Write your code here
a=int(input("a= Enter one number "))
b=int(input("b=Enter the second number "))
c=a
a=b
b=c
print("After swapping a =",a,"b=",b)

"""### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input."""

# first take a coardinate from users
import math
x1=int(input("Enter the x coordinate of 1st point : "))
y1=int(input("Enter the y coordinate of 1st point : "))
x2=int(input("Enter the x coordinate of 2st point : "))
y2=int(input("Enter the y coordinate of 2st point : "))
#apply dis formula
dis= math.sqrt((x1-x2)**2+(y1-y2)**2)
# print result
print("distance between point is ", dis)

"""### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user."""

# take all value form users
#Apply formula and calculate simple interest
# print result

principle=int(input("Enter the amount of principle :"))
rate = int(input("Enter the rate of interest :"))
time= int(input("Enter the time :"))
simple_interest = (principle * rate* time)/100
print(simple_interest)

"""### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example: Input: heads -> 4 legs -> 12

Output: dogs -> 2 chicken -> 2
"""

h=int(input("Enter the total number of heads:"))
l=int(input("Enter the total number of legs :"))
if h<=l:
  hen=int(2*h-l/2)
  dog=int(h-hen)

print("number of hen =",hen)
print("number of dog= ",dog)

"""### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user."""

num= int(input("Enter a nth number for finding sum of squares of first n natural number"))
sum=0
if num > 0:
  for i in range(1, num+1):
    sum=sum+(i*i)

  print("sum of square of first n natural numbers : ", sum)

else:
  print("your input is negative or 0")

"""### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user."""

# taking 1st , 2nd and nth number from users
# finding difference (2nd-1st)
# apply formula for finding nth term.

first=int(input("enter 1st term of an Arithmetic Series : "))
second=int(input("enter 2nd term of an Arithmentic series : "))
N= int(input("enter the Nth number : "))
d=second-first
Nth = first + (N-1)*d
print("Nth term of the series : ", Nth)

"""### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user."""

#Taking input of all numerator and denominator of numbers form users
n1=int(input("Enter numerator and denominator of 1st number : "))
d1=int(input("Enter the denominator of 1st number : "))
n2=int(input("Enter numerator of 2nd number : "))
d2=int(input("Enter the denominator of 2nd number : "))
num1=n1/d1
num2=n2/d2
print("Sum of two fraction", num1+num2)

"""###Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.

Input:
Dimensions of the milk tank
H = 20cm, L = 20cm, B = 20cm

Dimensions of the glass
h = 3cm, r = 1cm
"""

# taking all input form users

H=float(input("enter the height of milk tank: "))
L=float(input("Enter the length of milk tank: "))
B=float(input("Enter the Breath of milk tank: "))
h=float(input("enter the height of glass: "))
r=float(input("enter the radius of glass: "))
pie=3.14

volumn_milk_tank = H*L*B
volumn_glass=pie*r*r*h

no_of_glass=(volumn_milk_tank)/(volumn_glass)
print("Total number of glass of milk = ",no_of_glass)

